-- Obrisi stare usluge i kategorije
DELETE FROM appointment_services;
DELETE FROM services;
DELETE FROM service_categories;

-- Kategorije
INSERT INTO service_categories (naziv, redoslijed) VALUES
('Usluge', 1),
('Alma Harmony XL Pro', 2),
('Exion Face', 3),
('Exion Body', 4),
('Exion Frakcioni', 5),
('Exion Frakcioni - Tijelo', 6),
('EM Sculpt NEO', 7),
('EM Face', 8),
('Alma Soprano Titanium - Cijelo tijelo', 9),
('Paketi po regijama - Epilacija', 10),
('Pojedinacni tretmani - Epilacija', 11),
('Masaze', 12),
('Opsta Hirurgija', 13),
('Opsta stomatologija', 14),
('Konzervativa', 15),
('Protetika', 16),
('Endodoncija', 17),
('Oralna hirurgija', 18),
('Paradontopatija', 19),
('Estetska stomatologija', 20),
('Decija stomatologija', 21),
('Botox / Fileri', 22);

-- Usluge
INSERT INTO services (kategorija_id, naziv, cijena, trajanje) VALUES
-- Usluge
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Ljekarski pregled', 50, 30),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Specijalisticki pregled', 50, 30),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Specijalisticki pregled (gostujuci doktor)', 70, 30),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Specijalisticki kontrolni pregled', 30, 20),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Specijalisticki kontrolni pregled (gostujuci doktor)', 50, 20),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Intravenska infuzija (vitaminska inf. sa glutationom)', 65, 45),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Preso terapija', 30, 30),
((SELECT id FROM service_categories WHERE naziv='Usluge'), 'Paket 7 preso terapija', 190, 30),
-- Alma Harmony XL Pro
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Clear Skin Laser (akne/oziljci/rejuvenacija)', 200, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Clear Lift Laser (rejuvenacija/pigmentacije)', 200, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Clear Lift/Clear Skin (Lice+Vrat)', 250, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Clear Lift/Clear Skin (Lice+Vrat+Dekolte)', 300, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Lasersko uklanjanje tetovaza', 200, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Lasersko uklanjanje trajne sminke', 150, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Dye VL terapija (Rozacea/crvenilo)', 150, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Lasersko uklanjanje kapilara', 150, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'NIR (Infra red terapija)', 130, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Erbium Laser', 225, 45),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje virusnih bradavica - do 5', 80, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje virusnih bradavica - do 10', 100, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje virusnih bradavica - 10+', 150, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Lasersko uklanjanje kondiloma', 150, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje fibroma - do 5', 80, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje fibroma - do 10', 100, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje fibroma - 10+', 150, 30),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Lasersko uklanjanje keratoza', 50, 20),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje moluski kod djece - do 5', 80, 20),
((SELECT id FROM service_categories WHERE naziv='Alma Harmony XL Pro'), 'Uklanjanje moluski kod djece - do 10', 100, 20),
-- Exion Face
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Lice (Full Face)', 250, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Paket 4 tretmana + 2 gratis (Vrat/Dekolte)', 900, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Okoloocna regija', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Regija oko usana i usne', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Vrat', 100, 30),
((SELECT id FROM service_categories WHERE naziv='Exion Face'), 'Dekolte', 100, 30),
-- Exion Body
((SELECT id FROM service_categories WHERE naziv='Exion Body'), 'Velika regija (Stomak, Butine, Gluteus)', 250, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Body'), 'Mala regija (Listovi, Koljena, Nadlaktice, Sake)', 150, 45),
-- Exion Frakcioni
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Lice', 350, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Lice + Vrat', 420, 75),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Lice + Dekolte', 420, 75),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Lice + Vrat + Dekolte', 520, 90),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Vrat + Dekolte', 300, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni'), 'Paket 3 tretmana (Lice)', 900, 60),
-- Exion Frakcioni - Tijelo
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni - Tijelo'), 'Velika regija', 500, 60),
((SELECT id FROM service_categories WHERE naziv='Exion Frakcioni - Tijelo'), 'Velika + Mala regija', 550, 75),
-- EM Sculpt NEO
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS stomak', 300, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana stomak + 2 preso gratis', 1100, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS butine', 300, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana butine + 2 preso gratis', 1100, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS unutrasnja strana butina', 250, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana unutr. strana butina + 2 preso', 900, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS listovi', 250, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana listovi + 2 preso gratis', 900, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS biceps', 250, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana biceps + 2 preso gratis', 900, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS triceps', 250, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana triceps + 2 preso gratis', 900, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'EMS gluteus', 300, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), 'Paket 4 tretmana gluteus + 2 preso gratis', 1100, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), '2 Regije paket (2 velike) - 4 tretmana', 1950, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), '2 Regije paket (2 male) - 4 tretmana', 1750, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), '2 Regije paket (Mala+Velika) - 4 tretmana', 1850, 30),
((SELECT id FROM service_categories WHERE naziv='EM Sculpt NEO'), '4 Regije paket - 4 tretmana', 4500, 30),
-- EM Face
((SELECT id FROM service_categories WHERE naziv='EM Face'), '3 Regije (Celo, Obrazi, Submentum)', 450, 45),
((SELECT id FROM service_categories WHERE naziv='EM Face'), 'Paket 4 tretmana (3 regije) + 2 Exion gratis', 1600, 45),
((SELECT id FROM service_categories WHERE naziv='EM Face'), '2 Regije (Celo+Obrazi / Submentum+Obrazi)', 300, 30),
((SELECT id FROM service_categories WHERE naziv='EM Face'), 'Paket 4 tretmana (2 regije) + 2 Exion gratis', 1200, 30),
((SELECT id FROM service_categories WHERE naziv='EM Face'), '1 Regija (Celo / Obrazi / Podbradak)', 200, 20),
-- Alma Soprano Titanium
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Cijelo tijelo 7 tretmana - Muskarci', 1450, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Cijelo tijelo 7 tretmana - Zene', 1150, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Cijelo tijelo 10 tretmana - Muskarci', 1600, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Cijelo tijelo 10 tretmana - Zene', 1350, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Odrzavanje - Muskarci', 330, 60),
((SELECT id FROM service_categories WHERE naziv='Alma Soprano Titanium - Cijelo tijelo'), 'Odrzavanje - Zene', 200, 60),
-- Paketi po regijama - Epilacija
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Cijele noge - Muskarci', 800, 60),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Cijele noge - Zene', 500, 60),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Pola nogu - Zene', 250, 45),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Ruke - Zene', 250, 45),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Intimna regija - Zene', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Intimna regija sa Gluteusom - Zene', 320, 30),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Cijelo lice', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Prepone', 150, 20),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Pazuh', 150, 20),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Nausnice - Zene', 100, 15),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Ledja - Muskarci', 600, 60),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Stomak - Muskarci', 350, 45),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Grudi - Muskarci', 350, 45),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Cijele ruke - Muskarci', 400, 45),
((SELECT id FROM service_categories WHERE naziv='Paketi po regijama - Epilacija'), 'Ramena - Muskarci', 200, 30),
-- Pojedinacni tretmani - Epilacija
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Zene - Mala regija', 25, 15),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Zene - Srednja regija', 35, 20),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Zene - Velika regija', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Muskarci - Mala regija', 35, 15),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Muskarci - Srednja regija', 45, 20),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Muskarci - Velika regija', 65, 30),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Muskarci - Cijele noge', 80, 45),
((SELECT id FROM service_categories WHERE naziv='Pojedinacni tretmani - Epilacija'), 'Muskarci - Cijela ledja', 110, 45),
-- Masaze
((SELECT id FROM service_categories WHERE naziv='Masaze'), 'Relax (cijelo tijelo)', 70, 60),
((SELECT id FROM service_categories WHERE naziv='Masaze'), 'Relax (vrat, ramena, ledja)', 70, 45),
((SELECT id FROM service_categories WHERE naziv='Masaze'), 'Limfna drenaza', 60, 60),
((SELECT id FROM service_categories WHERE naziv='Masaze'), 'Sportska masaza', 65, 60),
((SELECT id FROM service_categories WHERE naziv='Masaze'), 'Terapijska masaza', 65, 60),
-- Opsta Hirurgija
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Specijalisticki pregled', 50, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Hirursko previjanje rane', 50, 20),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Hirurski debridman rane', 75, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Skidanje hirurskih konaca', 40, 15),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Obrada i usivanje rane', 80, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Obrada i usivanje rane - lice', 110, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Obrada i previjanje ulcus cruris', 80, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Obrada i previjanje opekotina', 95, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Obrada i previjanje dekubitusa', 90, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Hirurska intervencija uraslog nokta', 135, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje nokatne ploce', 110, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Hirursko lijecenje klavusa', 135, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Incizija apscesa', 95, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Ekscizija tromboziranog hemoroida', 150, 45),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Ekscizija nevusa', 115, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje ateroma', 70, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje dermatofibroma', 70, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje lipoma', 70, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje bradavica (do 10)', 80, 20),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje prekanceroza', 60, 20),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Eurbiopsija koznih promjena', 60, 20),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Vadjenje stranog tijela', 60, 20),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje krpelja', 60, 15),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje kondiloma (<10)', 90, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Uklanjanje kondiloma (>10)', 115, 30),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Punkcija ascita', 140, 45),
((SELECT id FROM service_categories WHERE naziv='Opsta Hirurgija'), 'Plasiranje urinarnog katetera', 50, 20),
-- Opsta stomatologija
((SELECT id FROM service_categories WHERE naziv='Opsta stomatologija'), 'Prvi pregled', 20, 15),
((SELECT id FROM service_categories WHERE naziv='Opsta stomatologija'), 'Kontrolni pregled', 10, 10),
((SELECT id FROM service_categories WHERE naziv='Opsta stomatologija'), 'Ukazivanje prve pomoci', 20, 15),
-- Konzervativa
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Prekrivanje pulpe', 30, 20),
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Kompozitni ispun (1 povrsina)', 40, 30),
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Kompozitni ispun (2 povrsine)', 50, 30),
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Kompozitni ispun (3 povrsine)', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Amalgamski ispun', 50, 30),
((SELECT id FROM service_categories WHERE naziv='Konzervativa'), 'Kompozitna faseta', 70, 30),
-- Protetika
((SELECT id FROM service_categories WHERE naziv='Protetika'), 'Helio nadogradnja sa fiberglass kocicem', 80, 45),
((SELECT id FROM service_categories WHERE naziv='Protetika'), 'Nadogradnja sa metalnim kocicem', 70, 45),
((SELECT id FROM service_categories WHERE naziv='Protetika'), 'Ljuspice', 250, 60),
-- Endodoncija
((SELECT id FROM service_categories WHERE naziv='Endodoncija'), 'Aplikacija lijeka', 20, 15),
((SELECT id FROM service_categories WHERE naziv='Endodoncija'), 'Mortalna amputacija', 30, 30),
((SELECT id FROM service_categories WHERE naziv='Endodoncija'), 'Vitalna amputacija', 30, 30),
((SELECT id FROM service_categories WHERE naziv='Endodoncija'), 'Drenaza oboljelog zuba', 20, 15),
((SELECT id FROM service_categories WHERE naziv='Endodoncija'), 'Definitivno punjenje po kanalu zuba', 30, 30),
-- Oralna hirurgija
((SELECT id FROM service_categories WHERE naziv='Oralna hirurgija'), 'Ekstrakcija stalnog zuba', 40, 20),
((SELECT id FROM service_categories WHERE naziv='Oralna hirurgija'), 'Komplikovana ekstrakcija', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Oralna hirurgija'), 'Incizija i drenaza apscesa', 40, 20),
-- Paradontopatija
((SELECT id FROM service_categories WHERE naziv='Paradontopatija'), 'Uklanjanje naslaga sa pjeskarenjem i poliranjem', 60, 30),
((SELECT id FROM service_categories WHERE naziv='Paradontopatija'), 'Kiretaza paradontalnog dzepa', 20, 15),
-- Estetska stomatologija
((SELECT id FROM service_categories WHERE naziv='Estetska stomatologija'), 'Ordinacijsko izbjeljivanje zuba po vilici', 150, 45),
((SELECT id FROM service_categories WHERE naziv='Estetska stomatologija'), 'Izbjeljivanje zuba sa folijama po vilici', 150, 45),
-- Decija stomatologija
((SELECT id FROM service_categories WHERE naziv='Decija stomatologija'), 'Ekstrakcija mlijecnog zuba', 20, 10),
((SELECT id FROM service_categories WHERE naziv='Decija stomatologija'), 'Zalivanje fisura po zubu', 20, 10),
-- Botox / Fileri
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (1 regija) - lokalni doktor', 100, 20),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (1 regija) - gostujuci doktor', 150, 20),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (2 regije) - lokalni doktor', 200, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (2 regije) - gostujuci doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (3 regije) - lokalni doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Botox (3 regije) - gostujuci doktor', 330, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Hiperdidroza', 300, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Filler 1ml - lokalni doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Filler 1ml - gostujuci doktor', 300, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Filler 5ml (4+1 gratis) - lokalni doktor', 1000, 45),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Korekcija nosa', 300, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Profhilo - lokalni doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Jalupro Super Hydro - lokalni doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Jalupro Young Eye - lokalni doktor', 160, 20),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'PRP - lokalni doktor', 200, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'PRP Cellular - lokalni doktor', 250, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Egzozomi - lokalni doktor', 200, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Topljenje fillera - lokalni doktor', 100, 15),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Nefertiti - lokalni doktor', 330, 45),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'Lipoliza - lokalni doktor', 200, 30),
((SELECT id FROM service_categories WHERE naziv='Botox / Fileri'), 'MOA GLAM (Botox 3 regije + 2ml fillera)', 660, 60);
